name: CI-Windows

on:
    schedule:
        - cron: "30 10 * * *"
    watch:
        types: [started]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Clone from gitee
              run: git clone --depth 1 https://gitee.com/bling_yshs/Yunzai-v3-Installation-Steps

            - name: Cd Copy AND REMOVE
              run: |
                  cd Yunzai-v3-Installation-Steps
                  cp -R -f * ../
                  cd ..
                  rm -rf Yunzai-v3-Installation-Steps
            - name: Commit files
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add .
                  git commit -a -m "Sync from gitee"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
