name: CI-Windows

on:
    schedule:
        - cron: "30 10 * * *"
    watch:
        types: [started]
    workflow_dispatch:

env:
    GITEE_LINK: https://gitee.com/bling_yshs/Yunzai-v3-Installation-Steps
    GITEE_REPO_NAME: Yunzai-v3-Installation-Steps

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Setup Go environment
              uses: actions/setup-go@v4.0.1

            - name: build
              run: |
                  GOOS=windows GOARCH=amd64 CGO_ENABLED=1 go build -o main.exe main.go
            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: latest-dev
                  path: main.exe
