name: CI-Windows

on:
    schedule:
        - cron: "30 10 * * *"
    watch:
        types: [started]
    workflow_dispatch:

env:
    GITEE_LINK: https://gitee.com/bling_yshs/Yunzai-v3-Installation-Steps
    GITEE_REPO_NAME: Yunzai-v3-Installation-Steps

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Clone from gitee
              run: git clone --depth 1 $GITEE_LINK

            - name: Cd copy and remove
              run: |
                  cd $GITEE_REPO_NAME
                  cp -R -f * ../
                  cd ..
                  rm -rf $GITEE_REPO_NAME
            - name: Commit files
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git add .
                  git commit -a -m "Sync from gitee" || echo "No changes to commit"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
