name: CI-Windows

on:
    schedule:
        - cron: "30 10 * * *"
    watch:
        types: [started]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Clone from gitee
              run: git clone --depth 1 https://gitee.com/bling_yshs/Yunzai-v3-Installation-Steps

            - name: Cd Copy AND REMOVE
              run: |
                  cd Yunzai-v3-Installation-Steps
                  cp -R -f * ../
                  cd ..
                  rm Yunzai-v3-Installation-Steps

            - name: Push
              run: |
                  git config user.name "bling-yshs"
                  git config user.email "test@qq.com"
                  git add .
                  git commit -m "GitHub Actions Make Star at time"
                  git push
