name: Build ImmortalWrt

on:
    workflow_dispatch:

env:
    CLONE_COMMAND: git clone -b mt7986 --depth 1 https://github.com/padavanonly/immortalwrtARM

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Clone immortalwrtARM repo
              run: $CLONE_COMMAND

            - name: Copy config and feed and diy_sh
              run: |
                  cp .config immortalwrtARM/
                  cp feed.conf.default immortalwrtARM/
                  cp diy.sh immortalwrtARM/
            - name: Build immortalwrtARM
              run: |
                  cd immortalwrtARM
                  ./diy.sh
                  ./scripts/feeds update -a && ./scripts/feeds install -a
                  make V=99

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: ImmortalWrt_build_files
                  path: bin\target
