name: Build ImmortalWrt

on:
    workflow_dispatch:

env:
    CLONE_COMMAND: git clone -b mt7986 --depth 1 https://github.com/padavanonly/immortalwrtARM

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone from github
              uses: actions/checkout@v3

            - name: Clone immortalwrtARM repo
              run: $CLONE_COMMAND

            - name: Copy config and feed and diy_sh
              run: |
                  cp .config immortalwrtARM/
                  cp feeds.conf.default immortalwrtARM/
                  cp diy.sh immortalwrtARM/
                  cd immortalwrtARM
                  
            - name: Get the dependency of immortalwrtARM
              run: |
                  cd immortalwrtARM
                  chmod +x diy.sh
                  ./diy.sh
                  cd ..
                  cp .config immortalwrtARM/
                  cp feeds.conf.default immortalwrtARM/
                  rm .config
                  cd immortalwrtARM

            - name: Upload config before build
              uses: actions/upload-artifact@v3
              with:
                  name: config before build
                  path: .config

            - name: Build immortalwrtARM
              run: |
                  cd immortalwrtARM
                  mkdir -p bin/targets&& echo "hello" > bin/targets/pwp.txt
                  echo "===========================================now pwd:"
                  pwd
                  echo "ls:"
                  ls

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: ImmortalWrt_build_files
                  path: immortalwrtARM/bin/targets
